apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-ingestion-init
  namespace: airflow-ingestion
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: airflow-init
          image: local/modern-data-platform-airflow-ingestion:latest
          command:
            - bash
            - -lc
            - |
              airflow db init && \
              airflow users create \
                --username admin \
                --password admin \
                --firstname Airflow \
                --lastname Admin \
                --role Admin \
                --email admin@example.com || true
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@airflow-ingestion-postgres.airflow-ingestion.svc.cluster.local:5432/airflow
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /opt/airflow/project/airflow_ingestion/dags
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
